### ISSUE TITLE
Module development

### ISSUE THREAD

**Issue by bbrtj** [bogdanovmn/perl-web-sitemap#3]
Hello! Thanks for the module, it is quite useful. Sadly also contains some flaws that could use a fix.
I'm willing to develop it a bit and either submit some pull requests (if you're still interested in maintaining it) or take over completely. 

I'm a CPAN author with a couple of modules at my hand, you can see my cpan profile here: https://metacpan.org/author/BRTASTIC

Let me know if you would still like to maintain the module (review my patches, make distributions for CPAN etc)

**Comment by bogdanovmn** [comment]
Hi!
Unfortunately, I don't remember my CPAN's credentials as well as  where it should be applied :) 
As I remember, CPAN has a service for a module maintain delegation? If you want I would try to delegate it to you :)

**Comment by bbrtj** [comment]
@bogdanovmn Thanks for replying!
The module occupies a very nice namespace, so it would be nice to recover access to it.
You can try logging in on https://pause.perl.org . If you succeed, you can make me a co-maintainer ("Add Comaintainers" in the sidebar) or if you're not interested in this module at all, an owner ("Transfer Primary Permissions").
Whichever you do, you will be required to specify a PAUSE user ID, just type in "BRTASTIC". Thank you.

Edit: just in case you don't remember, your username for pause.perl.org is `MBOGDANOV`, you just have to guess the password ;)

**Comment by bogdanovmn** [comment]
@brtastic I have added you to co-maintainers, check it out please

**Comment by bbrtj** [comment]
@bogdanovmn thank you, I can confirm I received the permissions.

I take it that you still want to be involved a bit. I will then develop the module on my fork in the coming days and open a pull request with all the commits I will release in the next CPAN version. Repository link will remain pointing to this main repository.

If you want you can also grant me write rights to the repository, but that won't change the need for pull requests - master is a protected branch and only repository owners can push to it directly.

**Comment by bogdanovmn** [comment]
@brtastic ok, lets start with PR and then will see :)
